server {
    listen 80;
    server_name localhost;

    location = /healthz {
        access_log off;
        default_type text/plain;
        return 200 "ok\n";
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Это магическая строка для SPA:
        try_files $uri $uri/ /index.html;
    }

    # Редирект ошибок на главную (опционально)
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
