"""baseline

Revision ID: 7803079bd1e8
Revises: 
Create Date: 2026-10-06 04:12:23.372212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7803079bd1e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tech_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('lesson_type_id', sa.Integer(), nullable=True),
    sa.Column('tema', sa.Text(), nullable=False),
    sa.Column('nomer_zanyatiya', sa.String(), nullable=True),
    sa.Column('ped_tech', sa.Text(), nullable=True),
    sa.Column('cel_zanyatiya', sa.Text(), nullable=True),
    sa.Column('zadachi_obuch', sa.Text(), nullable=True),
    sa.Column('zadachi_razv', sa.Text(), nullable=True),
    sa.Column('zadachi_vosp', sa.Text(), nullable=True),
    sa.Column('prognoz_result', sa.Text(), nullable=True),
    sa.Column('oborudovanie', sa.Text(), nullable=True),
    sa.Column('istochniki', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_cards_id'), 'tech_cards', ['id'], unique=False)
    op.create_table('tech_card_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tech_card_id', sa.Integer(), nullable=False),
    sa.Column('nomer_etapa', sa.Integer(), nullable=False),
    sa.Column('nazvanie_etapa', sa.String(), nullable=False),
    sa.Column('cel_etapa', sa.Text(), nullable=True),
    sa.Column('dlitelnost', sa.String(), nullable=True),
    sa.Column('deyatelnost_prepod', sa.Text(), nullable=True),
    sa.Column('deyatelnost_obuch', sa.Text(), nullable=True),
    sa.Column('formiruemye_kompetencii', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tech_card_id'], ['tech_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_card_stages_id'), 'tech_card_stages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tech_card_stages_id'), table_name='tech_card_stages')
    op.drop_table('tech_card_stages')
    op.drop_index(op.f('ix_tech_cards_id'), table_name='tech_cards')
    op.drop_table('tech_cards')
    # ### end Alembic commands ###
