events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    gzip  on;

    upstream auth_service { server auth:8000; }
    upstream schedule_service { server schedule:8000; }
    upstream techcard_service { server techcard:8000; }
    upstream frontend_service { server frontend:80; }

    server {
        listen 80;
        server_name _;

        # Глобальные настройки для API
        location /api/ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Маршруты к Auth Service
            location /api/auth/ { proxy_pass http://auth_service; }
            location /api/users/ { proxy_pass http://auth_service; }

            # Маршруты к Schedule Service
            location /api/schedule/ { proxy_pass http://schedule_service; }
            location /api/groups/ { proxy_pass http://schedule_service; }
            location /api/auditoriums/ { proxy_pass http://schedule_service; }

            # Маршруты к Techcard Service
            location /api/techcard/ { proxy_pass http://techcard_service; }
            location /api/techcards/ { proxy_pass http://techcard_service; }
        }

        # Frontend
        location / {
            proxy_pass http://frontend_service;
            proxy_set_header Host $host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
